/**************************************************************************
   FILE          :    sys_status.h
 
   PURPOSE       :     
 
   AUTHOR        :    K.M. Arun Kumar alias Arunkumar Murugeswaran
 
  KNOWN BUGS     :
	
  NOTE           :   
	
  CHANGE LOGS     :
	   
 **************************************************************************/
 
 /* to avoid this header file to be included more than once, conditional directive is used  */
#ifndef _SYS_STATUS_H
#define _SYS_STATUS_H

/* ---------------------- macro defination ------------------------------------------------ */
#define NO_ERROR_OCCURED               (0)
#define WARNING_OCCURED                (1)
#define ERROR_OCCURED                  (2)
#define FATAL_OCCURED                  (3)

/* ---------------------- data type defination -------------------------------------------- */
typedef enum 
{
	NO_ERROR, ERR_IO_CONFIG_NULL_PTR, ERR_PORT_WRITE_VAL, ERR_PORT_WRITE_INIT_VAL, ERR_IO_CH_WRITE_DATA,
	ERR_IO_CONFIG_INDEX_INVALID, ERR_IO_CH_INVALID, ERR_CONFIG_IO_CH_MATCH_INVALID, ERR_GPIO_FUNC_SET,  ERR_IO_CH_00_FUNC_SET, 
	ERR_TRACE_FUNC_SET, ERR_IO_CH_48_FUNC_SET, ERR_IO_CH_58_FUNC_SET, ERR_PORT1_PIN_FUNC_SET, ERR_PORT_INVALID,
    ERR_CONFIG_PORT_INIT_VAL, ERR_IO_CH_GPIO_FUNC_SET, ERR_SW_CH_GPIO_FUNC_SET, ERR_GPIO_INPUT_FUNC_STATE, ERR_PIN_SIGNAL,
	ERR_PORT0_IO_PIN, ERR_PORT1_IO_PIN,  ERR_GPIO_CH_SET_PORT, ERR_IO_PIN_RANGE,  ERR_IO_CH_24_PIN, ERR_IO_CH_32_TO_47,
	ERR_CONF_INDEX_IO_CH_NULL_PTR, ERR_PORT_TO_IO_CONF_NULL_PTR, ERR_MAX_SW_CH_EXCEEDS, ERR_CONSUCC_PARA, ERR_STR_TO_NUM_PARA,
	ERR_STR_PTR_NULL, ERR_GPIO_OUTPUT_DATA, ERR_INVALID_PORT, ERR_IO_CH_READ, ERR_IO_CH_TO_SW_CH,
	ERR_IO_CH_RESERVE_PIN_FUNC_SET, ERR_GPIO_OUTPUT_FUNC_STATE, ERR_SW_CH_NOT_MATCH_IO_CH, ERR_CONFIG_PIN_RANGE, 
	ERR_CONFIG_DEBUG_FUNC_SET, ERR_CONFIG_TRACE_FUNC_SET, ERR_IO_CONFIG_TABLE_LARGE, ERR_TEST_FAIL_1_CONSUCC_BITS, ERR_TEST_FAIL_0_CONSUCC_BITS,
	WARN_CUR_DATA_ID_DEV_DISABLED, ERR_KEYPAD_ROW_WRITE, ERR_KEYPAD_INVALID_ROW, ERR_KEYPAD_COL_INPUT, ERR_KEYPAD_NO_ACCESS_COL,
	ERR_CUR_DATA_ID_READ_EXCEEDS_MAX_CHARS, ERR_SW_NO_READ, ERR_SW_NO_ACCESS, ERR_READ_PORT_VAL, ERR_SEG7_NO_WRITE,
	SW_OR_KEY_NOT_PRESSED, CUR_DATA_ID_UNTIL_LAST_TRY_COMPLETE_READ_AND_READY_PROCESS, CUR_DATA_ID_REACH_MAX_CHARS_READ_WAIT_TERMINATOR_CHAR, CUR_DATA_ID_NUM_CHAR_READ, WARN_CUR_DATA_ID_SPECIAL_CHAR_READ_BUT_DISABLED, 
	ERR_KEYBOARD_READ_OPER, ERR_IO_CH_WRITE_NON_WRITE, ERR_PORT_WRITE_BIT_VAL, ERR_DATA_ID_EXCEED, ERR_NULL_PTR,
	ERR_FORMAT_INVALID, ERR_EXCEEDS_DATA_NUM_CHARS, ERR_DEV_SRC_ID_INVALID, ERR_ALREADY_MEM_ALLOC ,ERR_DATA_ID_CONF,
	ERR_DEV_CH_ID_EXCEEDS, ERR_DEV_CH_ID_OR_NULL_PTR, WARN_CUR_DATA_ID_DEV_NO_ACCESS, WARN_PREV_AND_CUR_DATA_MATCH, 
	ERR_SEG7_DISABLED, CUR_DATA_ID_SPECIAL_CHAR_READ, ERR_DEV_INIT, ERR_DEV_ALLOW_ACCESS, ERR_IO_CH_UNCONFIG,
	ERR_IO_CH_FUNC_RESET, ERR_DEV_OPER_DEINIT_FUNC, ERR_DEV_OPER_INIT_FUNC, ERR_DEV_OPER_NO_ACCESS_FUNC, ERR_DEV_OPER_ALLOW_ACCESS_FUNC, 
	ERR_DEV_OPER_READ_FUNC, ERR_DEV_OPER_OUTPUT_FUNC, CUR_DATA_ID_SMALL_ENGLISH_ALPHA_CHAR_READ, CUR_DATA_ID_BIG_ENGLISH_ALPHA_CHAR_READ, WARN_CUR_DATA_ID_NUM_CHAR_READ_BUT_DISABLED,
	WARN_CUR_DATA_ID_SMALL_ENGLISH_ALPHA_CHAR_READ_BUT_DISABLED, WARN_CUR_DATA_ID_BIG_ENGLISH_ALPHA_CHAR_READ_BUT_DISABLED, DATA_CHAR_READ, WARN_CUR_DATA_ID_CTRL_CHAR_READ_BUT_DISABLED, ERR_INVALID_DATA_CHAR_READ,
	CUR_DATA_ID_CTRL_CHAR_INPUT, CUR_DATA_ID_VALID_CHAR_READ, ERR_DEV_OPER_DISABLE_FUNC, ERR_DEV_OPER_ENABLE_FUNC, ERR_NO_INPUT_DEV, 
	ERR_INPUT_DEV_ID_OPER_FUNC, ERR_DEV_OPER_OPEN_FUNC, ERR_DEV_OPER_CLOSE_FUNC, ERR_NO_OUTPUT_DEV, ERR_INVALID_OUTPUT_DEV_OPER_FUNC, 
	ERR_INPUT_DEV_CH_ID_NOT_MATCH, ERR_OUTPUT_DEV_CH_ID_NOT_MATCH, ERR_DATA_TYPE_INVALID, ERR_NO_COMM_DEV, ERR_DEV_SRC_CH_ID_AND_FILTER_NOT_MATCH,
	ERR_DEV_SRC_BASIC_OPER_FUNC_INVALID, ERR_DEV_ID_CONF, ERR_CUR_DATA_ID_INVALID, ERR_CUR_DATA_DEV_SRC_ALLOW_NOT_SRC_LIST, ERR_LED_MATRIX_WRITE,
	ERR_SW_CONFIG, ERR_SW_CONFIG_FIXED_NOT_ALLOC, ERR_SW_CONFIG_DYNAMIC_NOT_ALLOC, ERR_LCD_WRITE, ERR_LCD_READ,
	ERR_LCD_INVALID_LOC, ERR_LCD_CONFIG_INVALID, ERR_IO_CH_READ_NON_READ, ERR_TEST_FAIL_VAL_CONSUCC_BITS, ERR_UART_INIT, 
	ERR_CHECK_GPIO_FUNC, ERR_NON_GPIO_FUNC_SET, ERR_COMM_TX_PROC, ERR_COMM_RCV_PROC, COMM_NO_RCV_CHAR, 
	COMM_RCVD_CHAR, ERR_DEV_OPER_RECEIVE_FUNC, ERR_LCD_DISP_FORMAT, ERR_UART_DISP_FORMAT, WARN_LCD_ALLOC_LESS_THAN_CONFIG_CHARS,
	ERR_LED_MATRIX_DATA_TYPE_INVALID, ERR_DEV_OPER_WRITE_FUNC, ERR_PROC_ERROR, WARN_LCD_TRY_CHAR_ATEND_CONF_LINE, WARN_LCD_TRY_BS_CHAR_ATBEGIN,
	VALID_BS_CHAR_READ, ERR_UART_OVERFLOW_RUN, ERR_UART_FRAMING, ERR_DEV_ID_INVALID, ERR_DEV_ID_NOT_MATCH,
	ERR_CUR_DATA_ID_INVALID_DATA_TYPE, ERR_UART_NUM_DISP, ERR_NEXT_DATA_CONF, ERR_LCD_DISP_GOTO_XY, ERR_LCD_INPUT_GOTO_XY,
	ERR_LCD_WRITE_OPER, ERR_APPL_DATA_RETRIEVE, ERR_LCD_DATA_POINT_CONFIG, ERR_UART_TX_PROC, ERR_UART_RCV_PROC,
	 ERR_KEYBOARD_ENTER_SW_OPER_BUT_NOT_CONFIG, ERR_KEYBOARD_BS_SW_OPER_BUT_NOT_CONFIG, ERR_KEYBOARD_PART_OPER, ERR_SW_PRESS_PROC, ERR_DEV_OPER_FUNC_PROC,
	 ERR_KEYBOARD_ENTER_SW_PROC, ERR_KEYBOARD_BS_SW_PROC, ERR_KEYBOARD_COL_SCAN_PROC, ERR_INVALID_DATA, VALID_ENTER_CHAR_READ, 
	 ERR_RESET_OPER, ERR_SW_NOT_ALLOC, ERR_SW_CH_INVALID, VALID_CTRL_CHAR_READ, ERR_HW_INIT,
	 CUR_DATA_ID_INPUT_MAX_TRIED, CUR_DATA_ID_NO_INPUT_DEV, ERR_COMM_DEV_ID_OPER_FUNC, ERR_OUTPUT_DEV_ID_OPER_FUNC, ERR_RESET_DATA_ID_STATUS,
	 CUR_DATA_ID_LAST_TRY_COMPLETE_READ_AND_READY_PROCESS, CUR_DATA_ID_COMPLETE_READ_AND_READY_PROCESS, NUM_SYS_STATUS 
} system_status_flags_t;

/* -------------------- public variable declaration --------------------------------------- */

extern uint32_t sys_error_or_warning_flag;

/* -------------------- public function declaration --------------------------------------- */

#endif

/*------------------------------------------------------------------*-
  ------------------------ END OF FILE ------------------------------
-*------------------------------------------------------------------*/
